### ISSUE TITLE
?

### ISSUE THREAD

**Issue by UsefullCoder** [ProdigyAPI/ProdigyXHack#332]
What happened to the membership hack?

**Comment by UsefullCoder** [comment]
SOMEBODY RESPOND!!!

**Comment by AgrTheDev** [comment]
Gone

**Comment by FailedCoder23** [comment]
The Discord server states this:
<br>
Removal of Membership Hacks
**We have removed membership type hacks** (normal, legacy) from Prodigy X due to a couple reasons:

**1. The hack didn't serve an important purpose as it was only temporary with the hack enabled and it also does not unlock all the features of real purchased membership.**

**2. With thousands amongst thousands of users toggling the hack daily, we decided it would be safest to remove the hack to avoid any legal issues in the future as toggling the hack cuts into Prodigy's revenue due to being able to access paid features for free.**

These changes are most likely **_permanent_** and **_will not be returning_** to Prodigy X.

**Comment by AgrTheDev** [comment]
ty

**Comment by UsefullCoder** [comment]
Thanks

**Comment by UsefullCoder** [comment]
Also @rxzyx has Membership Hacks
